### ISSUE TITLE
Add styles appears to fail during config parse 

### ISSUE THREAD

**Issue by Ieuanoh** [LekoArts/figma-theme-ui#17]
Hello, I'm trying to use the plugin to import a theme into Figma but when I add the config and click 'Add Styles', nothing happens. I get no verification in the UI and nothing in the console to suggest an error has occured. Whilst running the plugin in dev mode, I have traced the issue to the `JSON5.parse` method used in `parseConfig`. It seems to be failing silently and I cannot log the result and futher execution seems to stop. As a result, the type check in `code.ts` doesn't appear to be reached. 

There is perhaps something else going on as I haven't had all that much time to verify, but I have been using the config file in your Readme to test this with. 

I will be able to further investigate soon, but for now if you have any ideas as to why this is happening, any help would be great!

Here is the config object I am using:

```
module.exports = {
  fonts: {
    body:
      '-apple-system, BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"',
    heading: "inherit"
  },
  fontSizes: [12, 14, 16, 20, 24, 32],
  fontWeights: {
    body: 400,
    heading: 700
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125
  },
  colors: {
    text: "#000",
    background: "#fff",
    brand: {
      primary: "#07c",
      secondary: "#30c"
    },
    teal: [null, "#e6fffa", "#b2f5ea", "#81e6d9"]
  }
};

```

**Comment by LekoArts** [comment]
Thanks for the issue! The problem was the `;` at the end of the file. I fixed that and also tried to handle cases where backticks are used instead of single quotes.

**Comment by Ieuanoh** [comment]
Thanks! Much appreciated :)
